### PR TITLE
[Docker]: Adds Dockerfile for automated builds and publishing to Docker Hub

### PR DESCRIPTION
**Pull request by prologic**
Test Plan: Works

```#!bash
prologic@Jamess-MacBook
Sun Apr 29 22:03:22
~/go/src/github.com/wakeful/pve_exporter
 (master) 0
$ docker run -i -t prologic/pve_exporter
Usage of /pve_exporter:
  -listen-address string
    	Address on which to expose metrics. (default ":9090")
  -password string
    	Password for accessing PVE API (default "1234")
  -pve-url string
    	URL to your PVE control panel (default "https://127.0.0.1:8006")
  -realm string
    	PAM / LDAP auth method (default "pam")
  -telemetry-path string
    	Path under which to expose metrics. (default "/metrics")
  -timeout int
    	set request timeout to n (seconds) (default 5)
  -user string
    	User name used for accessing PVE API (default "root")
  -version
    	show version and exit
```

### CODE REVIEW

**Comment by prologic** [comment]
Image Details:

```#!bash
$ docker images prologic/pve_exporter
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
prologic/pve_exporter   latest              871835b56232        4 minutes ago       7.22MB
```

**Comment by prologic** [comment]
Have created an Automated Build [here](https://hub.docker.com/r/prologic/pve_exporter/)

**Comment by wakeful** [comment]
@prologic LGTM. Thank you.

**Comment by prologic** [comment]
Welcome :) I now have this running in my infra

**Pull request merged**
